spring.application.name=ExempleB3BDD
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=Soleil123
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=EtudiantB32027;encrypt=false